spring.application.name=iam-service
server.port=8081

# ===============================
# Database
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/iam_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
# ???: Flyway ?? ??????? ?? ????? ?????? ???????
# ?? ?????? update ?? ????? ???????
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# spring.flyway.baseline-on-migrate=true
# spring.flyway.baseline-version=0

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info

# ===============================
# Logging
# ===============================
logging.level.root=INFO
logging.level.com.cyphervault.iam=DEBUG

# ===============================
# JWT
# ===============================
security.jwt.secret=CypherVaultIamServiceJwtSecretKeyMustBeLongEnoughForHs256Algorithm123456
security.jwt.access-token-expiration-minutes=60

# ===============================
# Kafka
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.client-id=iam-service-producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.producer.acks=all
spring.kafka.producer.retries=10
spring.kafka.producer.properties.enable.idempotence=true
spring.kafka.producer.properties.spring.json.add.type.headers=false

# Topic
app.kafka.topics.user-public-key-registered=iam.user-public-key.registered.v1
app.kafka.topics.user-public-key-registered-partitions=3
app.kafka.topics.user-public-key-registered-replicas=1
# ===============================
# Swagger / OpenAPI
# ===============================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api/auth/v3/api-docs
springdoc.swagger-ui.persistAuthorization=true