server.port=8085
spring.application.name=fabric-orchestrator-service

# ===============================
# Kafka Consumer
# ===============================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=fabric-orchestrator-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=com.cyphervault.fabric.userkey.dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.cyphervault.fabric.userkey.dto.UserPublicKeyRegisteredEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.listener.ack-mode=manual

app.kafka.topics.user-public-key-registered=iam.user-public-key-registered.v1

# ===============================
# Fabric
# ===============================
fabric.channel-name=cyphervaultchannel
fabric.identity-chaincode-name=identity-registry-java

fabric.msp-id=Org1MSP
fabric.endorsing-orgs=Org1MSP,Org2MSP
fabric.peer-endpoint=192.168.6.134:7051
fabric.override-authority=peer0.org1.example.com

fabric.tls-cert-path=D:/project5th/cyphervault/infra/fabric/crypto/org1/peer0-org1-tls-ca.crt
fabric.cert-path=D:/project5th/cyphervault/infra/fabric/crypto/org1/user1-msp/signcerts/cert.pem
fabric.private-key-dir=D:/project5th/cyphervault/infra/fabric/crypto/org1/user1-msp/keystore

logging.level.root=INFO
logging.level.com.cyphervault.fabric=DEBUG

management.endpoints.web.exposure.include=health,info